# Generated by Django 4.1.2 on 2022-10-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_created_producto_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaprod',
            name='marca',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='categoriaprod',
            name='precio',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
