# Generated by Django 4.0.1 on 2022-01-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=70)),
                ('contenido', models.CharField(max_length=900)),
                ('contenido1', models.CharField(blank=True, max_length=600, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='servicio')),
            ],
            options={
                'verbose_name': 'presentacion',
                'verbose_name_plural': 'presentaciones',
            },
        ),
    ]
